// css
import 'styles/reset.css';
import 'styles/bundle.css';

// topbar
import 'components/topbar';
// main-nav
import 'components/main-nav';
// search
import 'components/search';
// fav-ad
import './components/fav-ad';
// xxsw
import './components/xxsw';
// jjzyx
import './components/jjzyx';
// ddwl
import './components/ddwl';
// tsddty
import './components/tsddty';
// zsj
import './components/zsj';
// gty
import './components/gty';
// footer-nav
import 'components/footer-nav';
// bottom-bar
import 'components/bottom-bar';
// backtotop
import 'components/backtotop';